theme: "PaperMod"
title: techlab.local.dev

enableRobotsTXT: true

# these settings force lastmod to only appear if set in the post.md
enableGitInfo: false
frontmatter:
  lastmod:
    - lastmod

menu:
  main:
    - name: Blog
      pageRef: /posts
      weight: 1
    - name: Search
      url: /search
      weight: 2
    - name: Resume
      url: /resume.pdf
      weight: 3
    - name: Archives
      url: /archives
      weight: 4
    # - name: Contact
    #   url: /contact
    #   weight: 5
    - name: Github
      url: https://github.com/kimdcottrell/
      weight: 6

minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"

params:
    description: "The writings of Kim D. Cottrell, a senior software developer and mid-level devops engineer."
    keywords: ["Kim's Tech Blog", "kimdcottrell", "Kim D. Cottrell", "Blog", "Portfolio", "Tech", "DevOps Engineer", "Software Engineer", "Full-Stack Engineer", "Web Development", "Web Design", "Remote Work", "Coffee", "Docker", "Containerization"]
    
    env: production

    author: kimdcottrell
    hideAuthor: true

    DateFormat: "January 2, 2006"

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowShareButtons: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true

    social:
      twitter: kimdcottrell

    socialIcons:
      - name: github
        title: See my active projects
        url: "https://github.com/kimdcottrell"
      - name: BlueSky
        title: Follow me on BlueSky
        url: "https://bsky.app/profile/kimdcottrell.com"
      - name: X
        title: Follow me on Twitter
        url: "https://x.com/kimdcottrell"
      - name: Threads
        title: Follow me on Threads
        url: "https://www.threads.net/@kimdcottrell"
      - name: LinkedIn
        title: Follow me on LinkedIn
        url: "https://www.linkedin.com/in/kimdcottrell"
      - name: Discord
        title: Chat with friends and I about something on Discord
        url: "https://discord.gg/cvDh7cRea2"
      - name: YouTube
        title: Watch me be a nerd
        url: "https://www.youtube.com/channel/UCx9pLB9CE-ZHuV_YFcXKV2g"

    homeInfoParams:
      Title: "Tech is neat."
      Content: >
        Hi there! I'm Kim D. Cottrell.
        
        - Senior software engineer. Mid-level devops engineer. Coffee enthusiast. Dog mom. ğŸ‘©â€ğŸ’»
        
        - I'm [available for hire](/resume.pdf) and looking for full-time, remote positions for devops, full-stack, platform, site-relability, and software engineer roles.

# this is required for search to work
outputs:
  home:
    - HTML
    - RSS
    - JSON





